
module.exports.config = {
  name: "predict",
  version: "2.0.0",
  hasPermssion: 0,
  credits: "Hridoy + GPT-5",
  description: "ভবিষ্যৎ বলে দেয় একদম হাসতে হাসতে 🤣",
  commandCategory: "Fun",
  usages: "predict",
  cooldowns: 5,
};

module.exports.run = async function ({ api, event }) {
  const predictions = [
    "তোর ভবিষ্যৎ এত উজ্জ্বল যে লোডশেডিংও ভয় পায় 😎",
    "তুই এমন বড়লোক হবি যে বিকাশেও লিমিট ছুঁইবি 💸",
    "তোর বউ তোরে ঘুমের মধ্যেও ঝাড়ি দিবে 😴💢",
    "তুই এমন famous হবি, meme page-গুলো তোকে দেবে royalty 😂",
    "তুই একদিন কফি খেতে যাস, কিন্তু bill দিবে তোর বন্ধুরা ☕🤣",
    "তুই এমন ঘুমকাতুরে হবি, alarm ঘড়িও resignation দিবে ⏰💀",
    "তোর crush একদিন বলবে — ‘ভাই, তুমি ভালো মানুষ!’ 😭",
    "তোর ফেসবুক status-এ Nobel Prize দিবে drama-এর জন্য 🎭",
    "তুই এমন smart হবি, গুগলও তোকে জিজ্ঞেস করবে ‘How?’ 🤖",
    "তুই এমন প্রেমে পড়বি, যে তোর WiFi-ও jealous হইবে 📶💔",
    "তোর exam এ পাস মার্ক দেখেই calculator hang হয়ে যাবে 🧮😂",
    "তুই এমন selfie তুলবি যে ক্যামেরা বলবে ‘Enough, bro!’ 📸😩",
    "তোর future এমন sweet, চিনি কোম্পানিও দেউলিয়া হবে 🍬🤣",
    "তুই এমন cool হবি, fridge তোকে respect দিবে 🧊😎",
    "তোর ঘুম এমন শক্তিশালী, ভূমিকম্পেও তুই নাড়বি না 😴🌍",
    "তুই এমন lucky হবি, কয়েন ছুড়লে দুই পাশেই হেড আসবে 🪙😆",
    "তোর মা তোকে দেখেই বলবে — ‘এই ছেলে আবার ফেসবুকে!’ 📱😂",
    "তুই এমন honest, exam-এ চিটিং করেও ফেল করবি 🤦‍♂️",
    "তুই এমন কিউট হবি, mosquito রাও কামড় দিতে দ্বিধা করবে 🦟💕",
    "তোর প্রেম শুরু হইবে meme comment section-এ 💬❤️",
    "তোর crush তোকে দেখে বলবে ‘ভাই, চা খাইবা?’ ☕💔",
    "তুই এমন boss হবি, কর্মচারীরা তোকে block দিবে 😭",
    "তোর বাড়িতে WiFi বন্ধ থাকলে সবাই তোরে দোষ দিবে 😡📶",
    "তোর মাথায় এমন আইডিয়া আসবে, Elon Musk panic করবে 🚀😂",
    "তোর প্রেমিকা এমন loyal হবি, অন্যরাই তোকে ছাড়বে 😩",
    "তুই এমন ধনী হবি, লুঙ্গির পকেটেও credit card রাখবি 💳🤣",
    "তোর laugh এমন কিউট, কুকুরও হেসে ফেলবে 🐶😂",
    "তোর চুলের স্টাইল দেখে পাখিরা বাসা বানাবে 🐦🤣",
    "তুই এমন cool হবি, তোর Ice Cream melt করবে না 🍦😎",
    "তোর মুখ দেখে Siri বলবে ‘Sorry, I don’t understand!’ 📱😂",
    "তোর luck এমন strong, লটারিতে জিতলেও ভুল করে cancel হবে 🎟️😭",
    "তুই এমন confused হবি, Google Map রোড হারাবে 🗺️😩",
    "তোর নাম শুনে calculator panic attack পাবে 🔢💀",
    "তোর future এমন ঝলমলে, Sunglass ছাড়া দেখা যাবে না 😎✨",
    "তুই এমন drama হবি, T-Series তোকে movie দিবে 🎬🤣",
    "তোর crush বলবে ‘তুমি ভাইয়ের মতো!’ — RIP 💔",
    "তোর ঘুম এমন গভীর, alarm এসে ক্ষমা চাইবে 😴",
    "তুই এমন cute হবি, তোর dp দেখে মানুষ হাসবে না কাঁদবে বুঝবে না 😆",
    "তোর handwriting দেখে font companies কাঁদবে ✍️😭",
    "তুই এমন gamer হবি, PUBG তোরে uninstall করবে 🎮😩",
    "তোর brain এমন fast, buffering ও হার মানবে ⚡🤯",
    "তোর love story Netflix-এর পরের সিরিজ হবে 📺❤️",
    "তুই এমন forgetful হবি, নিজের password ভুলে যাবি 🔑😂",
    "তোর ফোন তোরে বলবে ‘Bro, একটু rest দরকার!’ 📱💤",
    "তোর কানের পাশে mosquito বলবে ‘এই ভাই, শান্তি নাই!’ 🦟😡",
    "তুই এমন talkative হবি, Alexa তোকে mute করে দিবে 🎙️😅",
    "তোর crush তোকে reply দিবে — ‘Seen only’ 😭",
    "তোর চোখে এমন magic, ঘুমও resist করতে পারবে না 💤✨",
    "তোর ফেসবুক রিকোয়েস্টে শুধু bot accept দিবে 🤖💔",
    "তোর future এমন unpredictable, horoscope পল্টি খাবে 🔮😆"
  ];

  const randomPrediction = predictions[Math.floor(Math.random() * predictions.length)];
  api.sendMessage(`🔮 তোমার ভবিষ্যৎ বলছে:\n\n👉 ${randomPrediction}`, event.threadID);
};